### ISSUE TITLE
能不能提供markdown版本？

### ISSUE THREAD

**Issue by tintinyoung** [Walton1128/CPP-Templates-2nd--#1]

**Comment by Walton1128** [comment]
可以 等整体差不多了一起转成markdown

**Comment by riseOfCurse** [comment]
感谢！

**Comment by b-y-y** [comment]
template< 由逗号分割的模板参数> 尖括号里的不翻译感觉更好，一般写代码的这种简单的英文都会的；也可以在后面用注释来翻译

**Comment by b-y-y** [comment]
如果调用参数是按值传递的，那么只有退化（decay）这一类简单转换是被允许的：const 和 volatile 限制符会被忽略，引用被转换成被引用的类型，raw array 和函数被转换为相 应的指针类型。**通过模板类型参数 T 定义的两个参数，它们实参的类型在退化（decay） 后必须一样。**
粗体部分应该是:**通过模板类型参数 T 定义的两个参数，它们的退化类型(ignore const/raw array->pointer)必须一样。**
template<typename T>  
bool cmp( T t1, T t2 )
{
    return *t1 < *t2;
}  
int main()  
{
 int arr[ ] = { 1, 2,3 };  
    const int* p1 = arr;  
    int* p2 = arr;//lead toerror  
    const int* p2 = arr;//fine  
    cmp( p1, p2 );
}

**Comment by b-y-y** [comment]
。。。怎么好多code 被吃了，p1, p2都是指针来的

**Comment by Walton1128** [comment]
没有删code，原书也有错漏，有些翻译的时候没有补。感谢您的意见

**Comment by cooperwolfLee** [comment]
非常感谢你的无私分享，非常了不起。我也想参与翻译，不知如何参与进去？

**Comment by Walton1128** [comment]
> 非常感谢你的无私分享，非常了不起。我也想参与翻译，不知如何参与进去？

你好，感谢你的支持。我目前第一部分最后一章（第11章）即将翻译完了。后面第二部分和第三部分可能没有足够的时间逐章翻译了。但是会抽取一些有意思或者自己觉得有用的章节来翻译。如果你有兴趣的话，可以随便根据自己的兴趣翻译第二和第三部分的章节。如果你不嫌弃，可以放在我这里一起供大家分享，当然你也可以自己发布出去。

另外，我之前的11章翻译，也一定有很多问题，后面也要抽时间慢慢调整，如果你能提供修改意见，也十分感谢。

**Comment by stevenetease** [comment]
为什么不一章一章的提交呢，合在一起的话每次都要全部下载，而不能只下载对应的章节

**Comment by Walton1128** [comment]
> 为什么不一章一章的提交呢，合在一起的话每次都要全部下载，而不能只下载对应的章节
各有优缺点吧，后面一起更新总的和单独章节

**Comment by taseikyo** [comment]
同意，建议每个章节一个 md 文档，这样既容易让其他人也参与翻译，也方便进行纠错。

**Comment by Smartuil** [comment]
期待，大家可以一起编辑
