### ISSUE TITLE
我有个疑问，关键词explicit被翻译了, 可能不翻译理解起来更好

### ISSUE THREAD

**Issue by dentiscalprum** [Walton1128/CPP-Templates-2nd--#20]
在原书P69, 您翻译的pdf P64, explicit 应该不被翻译更好理解吧,
在 C++17 之前，这一方式（目前依然被支持）只有在与拷贝初始化对应的构造函数不是被显 式定义的时候才有效。
在C++17之前, 这一方式(目前依然被支持)只有在拷贝初始化对应的构造函数不被定义成explicit时才有效
即使它有显式的构造函数也是这样。
即使它的构造函数被定义成explicit也可以工作

**Comment by Walton1128** [comment]
谢谢  后面改一下  确实直接用explicit更容易抓到重点

**Comment by dentiscalprum** [comment]
嗯嗯，感谢无私付出。有了您的翻译真是事半功倍
