### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by coolxv** [Walton1128/CPP-Templates-2nd--#21]
![image](https://user-images.githubusercontent.com/12321831/93281653-18062b00-f7ff-11ea-9e93-38ff754c2742.png)

**Comment by coolxv** [comment]
![image](https://user-images.githubusercontent.com/12321831/93281927-c4e0a800-f7ff-11ea-8650-4ec62f155242.png)

**Comment by coolxv** [comment]
![image](https://user-images.githubusercontent.com/12321831/93852313-66766680-fce4-11ea-9b57-7ee21f6dfdf3.png)

**Comment by Walton1128** [comment]
感谢，下次提交第22章的时候一起修改。

**Comment by ThreeZhiWang** [comment]
98页第一行，不行的是

**Comment by coolxv** [comment]
![image](https://user-images.githubusercontent.com/12321831/94112316-d701bc80-fe77-11ea-9cc6-07b59d889fa0.png)

**Comment by Walton1128** [comment]
已改正上传

**Comment by coolxv** [comment]
![image](https://user-images.githubusercontent.com/12321831/94384959-6eb42300-0176-11eb-95ae-7295b6333ac4.png)

**Comment by ThreeZhiWang** [comment]
![Uploading 2020-10-10_143159.png…]()

**Comment by ThreeZhiWang** [comment]
![2020-10-10_143159](https://user-images.githubusercontent.com/1261785/95647896-cdc65000-0b05-11eb-9df3-3e198df80374.png)

**Comment by ThreeZhiWang** [comment]
注释有点问题，算笔误吧

![2020-10-10_152613](https://user-images.githubusercontent.com/1261785/95648882-23eac180-0b0d-11eb-979a-3471cbfeaf50.png)

**Comment by ThreeZhiWang** [comment]
![2020-10-27_145920](https://user-images.githubusercontent.com/1261785/97267451-28311180-1865-11eb-8078-291325d5fb6e.png)

**Comment by Walton1128** [comment]
> 
> 
> 注释有点问题，算笔误吧
> 
> ![2020-10-10_152613](https://user-images.githubusercontent.com/1261785/95648882-23eac180-0b0d-11eb-979a-3471cbfeaf50.png)

这个应该是partial specialization，重点在MyClass<>后面的这个尖括号

**Comment by Walton1128** [comment]
> 
> 
> ![2020-10-27_145920](https://user-images.githubusercontent.com/1261785/97267451-28311180-1865-11eb-8078-291325d5fb6e.png)

谢谢 已更正

**Comment by Walton1128** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/12321831/94384959-6eb42300-0176-11eb-95ae-7295b6333ac4.png)

谢谢 已改正
