### ISSUE TITLE
老哥老哥 你的这本书是那本书啊！

### ISSUE THREAD

**Issue by WuZhengqiang666** [Walton1128/CPP-Templates-2nd--#22]
老哥老哥 你的这本书是那本书啊！英文名字。谢谢我好想看到了一本和你的书差不多的书。
https://detail.tmall.com/item.htm?id=609777315913&ali_refid=a3_430582_1006:1121145746:N:zS7lu3s1ffbKiSTkf+Un2Ax5P/fwwjdS:e23fb5e3acfc593c4337e57194ef0f99&ali_trackid=1_e23fb5e3acfc593c4337e57194ef0f99&spm=a230r.1.14.6
![image](https://user-images.githubusercontent.com/49598775/99476043-c9a21380-298a-11eb-8c37-f29819cc4b0c.png)
![image](https://user-images.githubusercontent.com/49598775/99476179-0837ce00-298b-11eb-97be-ceaf010e0730.png)

**Comment by Walton1128** [comment]
这是第一版，不是最新的。
