### ISSUE TITLE
附录翻译

### ISSUE THREAD

**Issue by gungler** [Walton1128/CPP-Templates-2nd--#24]
希望加入此书的翻译，现有英文纸质书一本。

**Comment by Walton1128** [comment]
> 
> 
> 希望加入此书的翻译，现有英文纸质书一本。

热烈欢迎，目前第一部分翻译完毕，第二部分由https://github.com/r00tk1ts/cpp-templates-2nd即将翻译完毕，第三部分还差三章翻译完毕。你是要翻译附录吗？   我还有个计划，过段时间试着写一些关于stl源码的东西，有兴趣也可以一起。

**Comment by gungler** [comment]
已是的，已经开始翻译。
可以的话我就加入该计划。

**Comment by gungler** [comment]
是的，已经开始翻译。
可以的话我就加入该计划。
另外请提供一下联系方式，便于对翻译时的细节问题进行处理。

**Comment by Walton1128** [comment]
> 
> 
> 是的，已经开始翻译。
> 可以的话我就加入该计划。
> 另外请提供一下联系方式，便于对翻译时的细节问题进行处理。
微信：aifangwei0815  。你可以单开一个github项目，如果你愿意，到时候我可以直接整合进来。

**Comment by Walton1128** [comment]
> 
> 
> > 是的，已经开始翻译。
> > 可以的话我就加入该计划。
> > 另外请提供一下联系方式，便于对翻译时的细节问题进行处理。
> > 微信：aifangwei0815  。你可以单开一个github项目，如果你愿意，到时候我可以直接整合进来。

我一直试着和原书保持一致，但是似乎这样不便于协作和每次更新后的阅读。翻译第二部分的同仁用的是markdown，但是我觉得可能没有pdf看起来舒服。
