### ISSUE TITLE
争议——2.8 typedef

### ISSUE THREAD

**Issue by r00tk1ts** [Walton1128/CPP-Templates-2nd--#7]
![image](https://user-images.githubusercontent.com/30942613/88054807-88425880-cb90-11ea-8c32-27b2c5512d56.png)
我看了一下手里的实体书（2018年5月印刷），里面是没有这一冗余行的

**Comment by Walton1128** [comment]
感谢，pdf英文版有  我翻译的时候还很奇怪。再次感谢。
